Update user-interactions.md
prompt method name caused

(function (exports, require, module, __filename, __dirname) { 'use strict';
^
RangeError: Maximum call stack size exceeded